name: Terraform Advanced CI/CD

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  JOB_1-Terraform-CI:
    runs-on:
      group: my_runner_group

    defaults:
      run:
        working-directory:  environments/test

    steps:

      - name: STEP-1 -- Checkout Repo
        uses: actions/checkout@v4

      - name: STEP-2 -- Terraform FORMAT Check
        run: terraform fmt -check -recursive

      - name: STEP-3 -- LOGIN to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: STEP-4 -- Terraform INIT
        run: terraform init

      - name: STEP-5 -- Terraform VALIDATE
        run: terraform validate 

      - name: STEP-6 -- Terraform PLAN
        run: terraform plan
