name: Terraform Advanced CI/CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  JOB_1-Terraform-CI:
    if: github.event_name == 'pull_request'

    runs-on:
      group: my_runner_group

    defaults:
      run:
        working-directory:  environments/test

    steps:

      - name: STEP-1 -- Checkout Repo
        uses: actions/checkout@v4

      - name: STEP-2 -- Terraform FORMAT Check
        run: terraform fmt -check -recursive

      - name: STEP-3 -- LOGIN to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: STEP-4 -- Terraform INIT
        run: terraform init

      - name: STEP-5 -- Terraform VALIDATE
        run: terraform validate 

      - name: STEP-6 -- Terraform PLAN
        run: terraform plan


  JOB_2-Terraform-CD-PLAN:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on:
      group: my_runner_group

    defaults:
      run:
        working-directory: environments/test

    steps:

      - name: STEP-1 -- Checkout MAIN
        uses: actions/checkout@v4

      - name: STEP-2 -- Login to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: STEP-3 -- Terraform INIT
        run: terraform init

      - name: STEP-4 -- Terraform PLAN
        run: terraform plan -out=tfplan

      - name: STEP-5 -- Upload PLAN
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: environments/test/tfplan


  JOB_3-Terraform-APPLY:
    needs: JOB_2-Terraform-CD-PLAN

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    environment: TEST

    runs-on:
      group: my_runner_group

    defaults:
      run:
        working-directory: environments/test

    steps:

      - name: STEP-1 -- Checkout main
        uses: actions/checkout@v4

      - name: STEP-2 -- Login to Azure
        uses: azure/login@v3 
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: STEP-3 -- Terraform INIT
        run: terraform init

      - name: STEP-4 -- Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: environments/test

      - name: STEP-5 -- Terraform APPLY
        run: terraform apply tfplan


  JOB_4-Pipeline-Diagnostics:
    runs-on:
      group: my_runner_group

    if: always()
    
    steps:

      - name: STEP-1 -- Display Pipeline Result
        run: |
          echo: "==================================="
          echo: "Pipeline Diagnostics"
          echo: "==================================="
          echo: "Event: ${{ github.event_name }}"
          echo: "Branch/Ref: ${{ github.ref }}"
          echo: "Workflow: ${{ github.workflow }}"
          echo: "Run ID: ${{ github.run_id }}"

        